platforms = ['community_bridge', 'github', 'issuehunt', 'ko-fi', 'liberapay', 'open_collective', 'otechie', 'patreon', 'tidelift', 'custom']

FIlE_PATH = '.github/FUNDING.yml'

def sponsor(funding_site):
    message = ('# These are supported funding model platforms\n\n')
    for funding in funding_site:
        if funding in platforms:
            message += f'{funding}: {funding_site[funding]}\n'
    message += '\n# generated by vaibhavmule/sponsor, sponsor me at patreon: vaibhavmule\n'
    return message


def generate_file(content):
    pass


if __name__ == "__main__":
    funding_site = {
        'github': ['vaibhavmule', 'josephmancuso'],
        'patreon': 'vaibhavmule',
        'custom': 'https://www.paypal.me/VaibhavMule',
        'paypal': 'https://www.paypal.me/VaibhavMule',
    }
    print(sponsor(funding_site))